### ISSUE TITLE
Extension Proposal: OAuth credential exchange debugger

### ISSUE THREAD

**Issue by zackverham** [posit-dev/connect-extensions#4]
It would be really useful when debugging customer issues to have a shiny app that exposes some of the internal magic of the credential exchange. 

Specifically, being able to view the claims in both the user session token we give to the credentials endpoint, and the access token returned by the credential endpoint (assuming its a jwt) would be really helpful for helping debug any issues with your connect configuration (one example would be proxy settings causing issues, but the sky is the limit here)

**Comment by zackverham** [comment]
This would work by decoding the claims of the jwt without verifying the signature, which is the piece that maintains token integrity server-side. This would obviously be bad security practice if the token claims were being consumed by anything aside from human eyes, but if we are using it as a debugging tool, that seems like a safe tradeoff.

**Comment by zackverham** [comment]
Quick hack showing the details we can pull out of the user session token pretty trivially:

<img width="1240" alt="Screenshot 2024-09-19 at 1 15 58 PM" src="https://github.com/user-attachments/assets/c83ace30-b7b7-44a6-8b69-cb5593e6835b">

**Comment by zackverham** [comment]
David is one step ahead of me: https://github.com/posit-dev/connect-extensions/pull/5

**Comment by edavidaja** [comment]
resolved in #5
